name: deployment

on:
  workflow_call

jobs: 
  setup:
    uses: ./.github/workflows/setup.yml

  test:
    needs: setup
    uses: ./.github/workflows/test.yml

  apply:
    runs-on: ubuntu-latest
    steps:
     - name: deploy
       run: terraform plan
